URL_SERVICE = "https://674d3edb-3fff-49d8-831a-8c727a1b2fc5.serverhub.praktikum-services.ru/"
DOC_PATH = "/docs/"
LOG_MAIN_PATH = "/api/logs/main/"
USERS_TABLE_PATH = "/api/db/resources/user_model.csv"
CREATE_USER_PATH = "/api/v1/users/"
PRODUCTS_KITS_PATH = "/api/v1/products/kits/"